Public Class tbl_Items
	Public itcd As String = ""
	Public itdesc As String = ""
	Public itdesc2 As String = ""
	Public itdesc3 As String = ""
	Public itdesc_spec As String = ""
	Public itdesct As String = ""
	Public itdesct2 As String = ""
	Public itdesct3 As String = ""
	Public itnaturecd As String = ""
	Public ittypecd As String = ""
	Public itcatcd As String = ""
	Public itsubcatcd As String = ""
	Public itgroupcd As String = ""
	Public itsubcd As String = ""
	Public itsubcd2 As String = ""
	Public itsubcd3 As String = ""
	Public mrpcode As String = ""
	Public dinear As String = ""
	Public filament As String = ""
	Public twists As String = ""
	Public col As String = ""
	Public dimension As String = ""
    Public suppcd As String = ""
    Public location As String = ""
	Public tstamp As DateTime = Today()
End Class
