Public Class v_yarnOut
	Public outno As String = ""
	Public outdt As String = ""
	Public tran_type As String = ""
	Public refdocno As String = ""
	Public suppcd As String = ""
	Public remm As String = ""
	Public itcd As String = ""
	Public itdesc As String = ""
	Public grade As String = ""
	Public boxno_s As String = ""
	Public boxno As String = ""
	Public spools As String = ""
	Public kg_gr As String = ""
	Public cart_tearwt As String = ""
	Public spool_tearwt As String = ""
	Public kg_nt As String = ""
	Public id_yarn_out_det As String = ""
End Class
