Public Class tbl_Suppliers
	Public suppcd As String = ""
	Public name As String = ""
	Public namet As String = ""
	Public addr1 As String = ""
	Public addr2 As String = ""
	Public addr3 As String = ""
	Public addr1t As String = ""
	Public addr2t As String = ""
	Public addr3t As String = ""
	Public city As String = ""
	Public ctry As String = ""
	Public tel As String = ""
	Public fax As String = ""
    Public email As String = ""
    Public email_cc As String = ""
    Public contact As String = ""
	Public dyer As DateTime = "01/01/1900"
	Public scalloper As DateTime = "01/01/1900"
	Public greige As DateTime = "01/01/1900"
	Public import As Integer = 0 'this field does not exist in supplier but added here to help in code
	Public altcode As String = ""
	Public abbrev As String = ""
	Public crdays As String = ""
	Public crterms As String = ""
	Public paymode As String = ""
End Class
