Imports System.Data
Imports System.Data.SqlClient
Imports System.Text

Public Class InsertYarn
	'Private ds As New DataSet
	'Private Clsconfig As New clsConfig
	Private connStr As New classConnection

	Public Function InsertYarnIn(ByRef ParamYarnin As tbl_Yarn_in, ByRef msgerr As String, ByRef docno As String, ByVal loginEmpcd As String) As Boolean
		Dim conn As New SqlConnection(connStr.connection())
		conn.Open()
		Dim comm As New SqlCommand("", conn)
		Dim tran As SqlTransaction = conn.BeginTransaction
		comm.Transaction = tran
		comm.CommandType = CommandType.StoredProcedure
		comm.CommandText = "p_yarn_in_insert "
		With ParamYarnin
            comm.Parameters.AddWithValue("@docdt", .docdt)
			comm.Parameters.AddWithValue("@purno", .purno.Trim)
			comm.Parameters.AddWithValue("@sinvno", .sinvno.Trim)
			comm.Parameters.AddWithValue("@sinvdt", .sinvdt.Trim)
			comm.Parameters.AddWithValue("@suppcd", .suppcd.Trim)
			comm.Parameters.AddWithValue("@lotno_sup", .lotno_sup.Trim)
			comm.Parameters.AddWithValue("@srefno", .srefno.Trim)
			comm.Parameters.AddWithValue("@tran_type", .tran_type.Trim)
			comm.Parameters.AddWithValue("@remark", .remark.Trim)
			comm.Parameters.AddWithValue("@log_empcd", loginEmpcd.Trim)
		End With
		Dim da As New SqlDataAdapter(comm)
		Dim dt As New DataTable

		' Get the new docno generated by the stored procedure
		Try
			da.Fill(dt)
		Catch ex As Exception
			msgerr = ex.Message
			tran.Rollback()
			Return False
		End Try

		Dim newDocno As String = dt.Rows(0)("docno").ToString.Trim
		Dim i As Integer = 0
		Dim tbl_Yarn_in_det As New tbl_Yarn_in_det

		docno = newDocno

		Try
			For Each tbl_Yarn_in_det In ParamYarnin.tbl_Yarn_in_det
				'comm = New SqlCommand("", conn)
				'comm.CommandType = CommandType.StoredProcedure
				comm.CommandText = "p_yarn_in_det_insert"
				comm.Parameters.Clear()
				With tbl_Yarn_in_det
					comm.Parameters.AddWithValue("@docno", newDocno.Trim)
					comm.Parameters.AddWithValue("@itcd", .itcd.Trim)
					comm.Parameters.AddWithValue("@boxno_s", .boxno_s.Trim)
					comm.Parameters.AddWithValue("@spools", .spools.ToString)
					comm.Parameters.AddWithValue("@grade", .grade.Trim)
					comm.Parameters.AddWithValue("@kg_gr", .kg_gr.ToString)
					comm.Parameters.AddWithValue("@cart_tearwt", .cart_tearwt.ToString)
					comm.Parameters.AddWithValue("@spool_tearwt", .spool_tearwt.ToString)
					comm.Parameters.AddWithValue("@kg_nt", .kg_nt.ToString)
					comm.Parameters.AddWithValue("@id_jobdet", .id_jobdet.ToString)
					comm.Parameters.AddWithValue("@log_empcd", loginEmpcd)
				End With
				da = New SqlDataAdapter(comm)
				dt = New DataTable
				da.Fill(dt)
				ParamYarnin.tbl_Yarn_in_det(i).boxno = dt.Rows(0)("boxno").ToString.Trim
				i += 1
			Next
		Catch ex As Exception
			msgerr = ex.Message
			tran.Rollback()
			Return False
		End Try
		tran.Commit()
		Return True
	End Function

	Public Function InsertYarnInReturn(ByVal ParamYarnin As tbl_Yarn_in, ByRef msgerr As String, ByRef Purno As String, ByVal loginempcd As String) As Boolean
		Dim conn As New SqlConnection(connStr.connection())
		conn.Open()

		Dim comm As New SqlCommand("", conn)
		Dim tran As SqlTransaction = conn.BeginTransaction
		comm.Transaction = tran
		comm.CommandType = CommandType.StoredProcedure
		comm.CommandText = "p_yarn_in_return_insert"
		With ParamYarnin
			comm.Parameters.AddWithValue("@docdt", .docdt)
			comm.Parameters.AddWithValue("@tran_type", .tran_type.Trim)
			comm.Parameters.AddWithValue("@outno", .outno.Trim)
			comm.Parameters.AddWithValue("@remark", .remark.Trim)
			comm.Parameters.AddWithValue("@log_empcd", loginempcd.Trim)
		End With
		Dim da As New SqlDataAdapter(comm)
		Dim dt As New DataTable

		Try
			da.Fill(dt)
		Catch ex As Exception
			msgerr = ex.Message
			tran.Rollback()
			Return False
		End Try

		Dim docno As String = dt.Rows(0)("docno").ToString.Trim
		Dim i As Integer = 0
		Dim tbl_Yarn_in_det As New tbl_Yarn_in_det
		Purno = docno

		Try
			For Each tbl_Yarn_in_det In ParamYarnin.tbl_Yarn_in_det
				comm.CommandType = CommandType.StoredProcedure
				comm.Transaction = tran
				comm.CommandText = "p_yarn_in_return_det_insert"
				comm.Parameters.Clear()

				With tbl_Yarn_in_det
					comm.Parameters.AddWithValue("@docno", docno.Trim)
					comm.Parameters.AddWithValue("@itcd", .itcd.Trim)
					comm.Parameters.AddWithValue("@boxno", .boxno.Trim)
					comm.Parameters.AddWithValue("@spools", .spools.ToString)
					comm.Parameters.AddWithValue("@grade", .grade.Trim)
					comm.Parameters.AddWithValue("@kg_gr", .kg_gr.ToString)
					comm.Parameters.AddWithValue("@cart_tearwt", .cart_tearwt.ToString)
					comm.Parameters.AddWithValue("@spool_tearwt", .spool_tearwt.ToString)
					comm.Parameters.AddWithValue("@kg_nt", .kg_nt.ToString)
					comm.Parameters.AddWithValue("@used", .Used.ToString)
					comm.Parameters.AddWithValue("@log_empcd", loginempcd.Trim)
				End With
				da = New SqlDataAdapter(comm)
				dt = New DataTable
				da.Fill(dt)
				ParamYarnin.tbl_Yarn_in_det(i).boxno = dt.Rows(0)("boxno").ToString.Trim
				i += 1
			Next
		Catch ex As Exception
			msgerr = ex.Message
			tran.Rollback()
			Return False
		End Try
		tran.Commit()
		Return True
	End Function

	Public Function CheckKeySGN_of_Month(ByVal Num As Integer, ByVal idname As String) As String
		Dim conn As New SqlConnection(connStr.connection())

		conn.Open()
		Dim comm As New SqlCommand("", conn)
		comm.CommandType = CommandType.StoredProcedure
		comm.CommandText = "p_num_select"
		comm.Parameters.AddWithValue("@idname", idname.Trim)
		comm.Parameters.AddWithValue("@yr", Year(Today()).ToString)
		Dim da As New SqlDataAdapter(comm)
		Dim dt As New DataTable
		Dim KeyMM As String = ""

		Try
			da.Fill(dt)
		Catch ex As Exception
			Return KeyMM
		End Try

		If dt.Rows.Count > 0 Then
			If dt.Rows(0)("format").ToString.Trim.ToUpper = "YY" Then
				KeyMM = Val(dt.Rows(0)("num")).ToString
			Else
				KeyMM = Val(dt.Rows(0)("num" & Num)).ToString
			End If
		End If
		Return KeyMM
	End Function

	Public Function InsertYarnOut(ByRef paramtbl_yarn_out As tbl_Yarn_out, ByRef Youtno As String, ByRef msgerr As String, ByVal loginEmpcd As String) As Boolean
		Dim conn As New SqlConnection(connStr.connection())
		conn.Open()

		Dim comm As New SqlCommand("", conn)
		Dim tran As SqlTransaction = conn.BeginTransaction
		comm.Transaction = tran
		comm.CommandType = CommandType.StoredProcedure
		comm.CommandText = "p_yarn_out_insert "
		With paramtbl_yarn_out
			comm.Parameters.AddWithValue("@outdt", .outdt.Trim)
			comm.Parameters.AddWithValue("@tran_type", .tran_type.Trim)
			comm.Parameters.AddWithValue("@refdocno", .refdocno.Trim)
			comm.Parameters.AddWithValue("@suppcd", .suppcd.Trim)
			comm.Parameters.AddWithValue("@kono", .kono.Trim)
			comm.Parameters.AddWithValue("@rem", .remm.Trim)
			comm.Parameters.AddWithValue("@log_empcd", loginEmpcd.Trim)
		End With
		Dim da As New SqlDataAdapter(comm)
		Dim dt As New DataTable

		Try
			da.Fill(dt)
		Catch ex As Exception
			msgerr = ex.Message
			tran.Rollback()
			Return False
		End Try

		Dim docno As String = dt.Rows(0)("outno").ToString.Trim
		Dim i As Integer = 0
		Dim tbl_Yarn_out_det As New tbl_Yarn_out_det
		Youtno = docno

		Try
			For Each tbl_Yarn_out_det In paramtbl_yarn_out.tbl_Yarn_out_det
				comm = New SqlCommand("", conn)
				comm.CommandType = CommandType.StoredProcedure
				comm.Transaction = tran
				comm.CommandText = "p_yarn_out_det_insert"
				With tbl_Yarn_out_det
					comm.Parameters.AddWithValue("@outno", docno.Trim)
					comm.Parameters.AddWithValue("@itcd", .itcd.Trim)
					comm.Parameters.AddWithValue("@grade", .grade.Trim)
					comm.Parameters.AddWithValue("@boxno", .boxno.Trim)
					comm.Parameters.AddWithValue("@id_job_det_yarn", .id_job_det_yarn.ToString)
				End With
				da = New SqlDataAdapter(comm)
				dt = New DataTable
				da.Fill(dt)
				paramtbl_yarn_out.tbl_Yarn_out_det(i).id_yarn_out_det = dt.Rows(0)("id_yarn_out_det")
				i += 1
			Next
		Catch ex As Exception
			msgerr = ex.Message
			tran.Rollback()
			Return False
		End Try
		tran.Commit()
		Return True
	End Function

	Public Function InsertJobOrderforYarn(ByVal tbl_job As tbl_job, ByRef SGN As String, ByRef msgerr As String, ByVal loginEmpcd As String) As Boolean
		Dim conn As New SqlConnection(connStr.connection())
		conn.Open()

		Dim comm As New SqlCommand("", conn)
		Dim tran As SqlTransaction = conn.BeginTransaction
		comm.Transaction = tran
		comm.CommandType = CommandType.StoredProcedure
		comm.CommandText = "p_job_insert"
		With tbl_job
			comm.Parameters.AddWithValue("@jobno", .jobno.Trim)
			comm.Parameters.AddWithValue("@jobdt", .jobdt)
			comm.Parameters.AddWithValue("@suppcd", .suppcd.Trim)
			comm.Parameters.AddWithValue("@supquoteno", .supquoteno.Trim)
			comm.Parameters.AddWithValue("@sourcedocno", .sourcedocno.Trim)
			comm.Parameters.AddWithValue("@supplang", .supplang.Trim)
			comm.Parameters.AddWithValue("@empcd", .empcd.Trim)
			comm.Parameters.AddWithValue("@deptcd", .deptcd.Trim)
			comm.Parameters.AddWithValue("@kono", .kono.Trim)
			comm.Parameters.AddWithValue("@delidt", .delidt)
			comm.Parameters.AddWithValue("@jobtype", .jobtype.Trim)
			comm.Parameters.AddWithValue("@jobitcd", .jobitcd.Trim)
			comm.Parameters.AddWithValue("@tubeqty", .tubeqty.ToString)
			comm.Parameters.AddWithValue("@tubekg", .tubekg.ToString)
			comm.Parameters.AddWithValue("@twists", .twists.Trim)
			comm.Parameters.AddWithValue("@col", .col.Trim)
			comm.Parameters.AddWithValue("@packcd", .packcd.Trim)
			comm.Parameters.AddWithValue("@splins", .splins.Trim)
			comm.Parameters.AddWithValue("@rem", .remark.Trim)
			comm.Parameters.AddWithValue("@deliaddr", .deliaddr.Trim)
			comm.Parameters.AddWithValue("@log_empcd", loginEmpcd.Trim)
		End With
		Dim da As New SqlDataAdapter(comm)
		Dim dt As New DataTable

		Try
			da.Fill(dt)
		Catch ex As Exception
			msgerr = ex.Message
			tran.Rollback()
			Return False
		End Try

		Dim docno As String = dt.Rows(0)("jobno").ToString.Trim
		Dim i As Integer = 0
		Dim j As Integer = 0
		Dim tbl_job_det As New tbl_job_det
		Dim tbl_job_det_yarn As New tbl_job_det_yarn
		SGN = docno

		Try
			For Each tbl_job_det In tbl_job.tbl_job_det
				comm = New SqlCommand("", conn)
				comm.CommandType = CommandType.StoredProcedure
				comm.Transaction = tran
				comm.CommandText = "p_job_det_insert "
				With tbl_job_det
					comm.Parameters.AddWithValue("@jobno", SGN)
					comm.Parameters.AddWithValue("@itcd", .itcd.Trim)
					comm.Parameters.AddWithValue("@itdesc", .itdesc.Trim)
					comm.Parameters.AddWithValue("@qty", .qty.ToString)
					comm.Parameters.AddWithValue("@uom", .uom.Trim)
					comm.Parameters.AddWithValue("@rem", .remark.Trim)
				End With
				da = New SqlDataAdapter(comm)
				dt = New DataTable
				da.Fill(dt)

				tbl_job.tbl_job_det(i).id_jobdet = dt.Rows(0)("id_jobdet")
				j = 0

				For Each tbl_job_det_yarn In tbl_job.tbl_job_det_yarn
					If tbl_job_det.itcd.Trim = tbl_job_det_yarn.itcd.Trim Then
						comm = New SqlCommand("", conn)
						comm.CommandType = CommandType.StoredProcedure
						comm.Transaction = tran
						comm.CommandText = "p_job_det_yarn_insert"
						With tbl_job_det_yarn
							comm.Parameters.AddWithValue("@id_job_det", tbl_job.tbl_job_det(i).id_jobdet.ToString)
							comm.Parameters.AddWithValue("@itcd", .itcd.Trim)
							comm.Parameters.AddWithValue("@boxno", .boxno.Trim)
							comm.Parameters.AddWithValue("@spools", .spools.ToString)
							comm.Parameters.AddWithValue("@kg_gr", .kg_gr.ToString)
							comm.Parameters.AddWithValue("@kg_nt", .kg_nt.ToString)
						End With
						da = New SqlDataAdapter(comm)
						dt = New DataTable
						da.Fill(dt)
						tbl_job.tbl_job_det_yarn(j).id_job_det_yarn = dt.Rows(0)("id_job_det_yarn")
					End If
					j += 1
				Next
				i += 1
			Next
		Catch ex As Exception
			msgerr = ex.Message
			tran.Rollback()
			Return False
		End Try
		tran.Commit()
		Return True
	End Function

	Public Function InsertYarnMaster(ByVal Param_tbl_items As tbl_Items, ByRef msgerr As String) As Boolean
		Dim conn As New SqlConnection(connStr.connection())
		conn.Open()

		Dim comm As New SqlCommand("", conn)
		Dim tran As SqlTransaction = conn.BeginTransaction
		comm.Transaction = tran
		comm.CommandType = CommandType.StoredProcedure
		comm.CommandText = "p_items_insert"
		With Param_tbl_items
			comm.Parameters.AddWithValue("@itcd", .itcd.Trim)
			comm.Parameters.AddWithValue("@itdesc", .itdesc.Trim)
			comm.Parameters.AddWithValue("@itdesc2", .itdesc2.Trim)
			comm.Parameters.AddWithValue("@itdesc3", .itdesc3.Trim)
			comm.Parameters.AddWithValue("@itdesc_spec", .itdesc_spec.Trim)
			comm.Parameters.AddWithValue("@itdesct", .itdesct.Trim)
			comm.Parameters.AddWithValue("@itdesct2", .itdesct2.Trim)
			comm.Parameters.AddWithValue("@itdesct3", .itdesct3)
			comm.Parameters.AddWithValue("@itnaturecd", .itnaturecd.Trim)
			comm.Parameters.AddWithValue("@ittypecd", .ittypecd.Trim)
			comm.Parameters.AddWithValue("@itcatcd", .itcatcd.Trim)
			comm.Parameters.AddWithValue("@itsubcatcd", .itsubcatcd.Trim)
			comm.Parameters.AddWithValue("@itgroupcd", .itgroupcd.Trim)
			comm.Parameters.AddWithValue("@itsubcd", .itsubcd.Trim)
			comm.Parameters.AddWithValue("@itsubcd2", .itsubcd2.Trim)
			comm.Parameters.AddWithValue("@itsubcd3", .itsubcd3.Trim)
			comm.Parameters.AddWithValue("@mrpcode", .mrpcode.Trim)
			comm.Parameters.AddWithValue("@dinear", .dinear.Trim)
			comm.Parameters.AddWithValue("@filament", .filament.Trim)
			comm.Parameters.AddWithValue("@twists", .twists.Trim)
			comm.Parameters.AddWithValue("@col", .col.Trim)
			comm.Parameters.AddWithValue("@dimension", .dimension.Trim)
			comm.Parameters.AddWithValue("@suppcd", .suppcd.Trim)
		End With
		Dim da As New SqlDataAdapter(comm)
		Dim dt As New DataTable

		Try
			da.Fill(dt)
		Catch ex As Exception
			msgerr = ex.Message
			tran.Rollback()
			Return False
		End Try
		tran.Commit()
		Return True
	End Function

End Class
